# Generated by Django 4.0.2 on 2022-02-20 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwikapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kwik',
            old_name='pub_date',
            new_name='kwik_date',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('kwik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='kwikapp.kwik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
