# Generated by Django 4.0.2 on 2022-06-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwikapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='about',
            field=models.TextField(blank=True, max_length=300, verbose_name='about'),
        ),
    ]
