# Generated by Django 4.0.2 on 2022-02-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwikapp', '0002_rename_pub_date_kwik_kwik_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentPost',
            new_name='CommentKwik',
        ),
    ]
