# Generated by Django 4.0.2 on 2022-05-23 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwikapp', '0006_userfollowing_userfollowing_unique_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwik',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
