# Generated by Django 4.0.2 on 2022-05-23 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwikapp', '0007_kwik_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kwik',
            name='like',
        ),
        migrations.AddField(
            model_name='kwik',
            name='like',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
