# Generated by Django 4.0.2 on 2022-05-26 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kwikapp', '0008_remove_kwik_like_kwik_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kwik',
            name='like',
        ),
        migrations.CreateModel(
            name='LikeKwik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kwik', to='kwikapp.kwik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
