# Generated by Django 4.0.2 on 2022-05-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwikapp', '0009_remove_kwik_like_likekwik'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likekwik',
            constraint=models.UniqueConstraint(fields=('kwik', 'user'), name='unique_like'),
        ),
    ]
